services:
  postgres:
    image: postgres:latest
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ecommerce
    ports:
      - '5432:5432'
  app:
    build: .
    container_name: ecommerce_backend
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgresql://dev:dev@postgres:5432/ecommerce
    depends_on:
      - postgres
